# Generated by Django 4.1.2 on 2023-09-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="notice",
            field=models.BooleanField(default=True),
        ),
    ]
